<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

use App\Models\{BiometricDeviceStatus, BiometricDevice, Area};

class BiometricDeviceSeeder extends Seeder
{
    public function run(): void {
        $biometric_statuses = [
            'active' => BiometricDeviceStatus::where('name', 'active')->first(),
        ];
        $areas = [
            'annex' => Area::where('name', 'Admin Annex')->first(),
            'admin' => Area::where('name', 'Main Admin')->first(),
            'agri' => Area::where('name', 'College of Agriculture')->first(),
            'cas' => Area::where('name', 'College of Arts and Sciences')->first(),
            'cbm' => Area::where('name', 'College of Business and Management')->first(),
            'cebrem' => Area::where('name', 'CEBREM')->first(),
            'cfes' => Area::where('name', 'College of Forestry and Natural Resources')->first(),
            'che' => Area::where('name', 'College of Human Ecology')->first(),
            'cisc' => Area::where('name', 'College of Information and Communication Technology')->first(),
            'cmu_press' => Area::where('name', 'CMU Press')->first(),
            'cmulhs' => Area::where('name', 'CMULHS')->first(),
            'coe' => Area::where('name', 'College of Engineering')->first(),
            'con' => Area::where('name', 'College of Nursing')->first(),
            'cvm' => Area::where('name', 'College of Veterinary Medicine')->first(),
            'odt' => Area::where('name', 'ODT')->first(),
            'coed' => Area::where('name', 'College of Education')->first(),
            'ogs' => Area::where('name', 'Office of General Services')->first(),
            'hospital' => Area::where('name', 'Hospital')->first(),
            'library' => Area::where('name', 'Library')->first(),
            'oasp' => Area::where('name', 'OASP')->first(),
            'osa' => Area::where('name', 'OSA')->first(),
            'prio' => Area::where('name', 'PRIO')->first(),
            'extension' => Area::where('name', 'Extension')->first(),
            'orgm' => Area::where('name', 'ORGM')->first(),
            'oss' => Area::where('name', 'Office of Security Services')->first(),
            'ucc' => Area::where('name', 'UCC')->first(),
            'uh' => Area::where('name', 'UCC')->first(),
        ];


        $data = [
            [
                'biometric_device_status_id' => $biometric_statuses['active']->id,
                'area_id' => $areas['annex']->id,
                'name' =>    'Admin Annex',
                'serial' =>  'XXXXX1',
                'model' =>   'XXX',
                'user_count' => 777,
                'fingerprint_count' => 123,
                'ip_address' => '0.0.0.1',
                'port' =>      4370,
                'status_at' => now(),
            ],
            [
                'biometric_device_status_id' => $biometric_statuses['active']->id,
                'area_id' => $areas['admin']->id,
                'name' =>    'Admin 1 VP Side',
                'serial' =>  'XXXXX2',
                'model' =>   'XXX',
                'user_count' => 777,
                'fingerprint_count' => 123,
                'ip_address' => '0.0.0.2',
                'port' =>      4370,
                'status_at' => now(),
            ],
            [
                'biometric_device_status_id' => $biometric_statuses['active']->id,
                'area_id' => $areas['admin']->id,
                'name' =>    'Admin 1 VP Accounting Side',
                'serial' =>  'XXXXX3',
                'model' =>   'XXX',
                'user_count' => 777,
                'fingerprint_count' => 123,
                'ip_address' => '0.0.0.3',
                'port' =>      4370,
                'status_at' => now(),
            ],
            [
                'biometric_device_status_id' => $biometric_statuses['active']->id,
                'area_id' => $areas['agri']->id,
                'name' =>    'Agri Cluster',
                'serial' =>  'XXXXX4',
                'model' =>   'XXX',
                'user_count' => 777,
                'fingerprint_count' => 123,
                'ip_address' => '0.0.0.4',
                'port' =>      4370,
                'status_at' => now(),
            ],
            [
                'biometric_device_status_id' => $biometric_statuses['active']->id,
                'area_id' => $areas['agri']->id,
                'name' =>    'Agri Main',
                'serial' =>  'XXXXX5',
                'model' =>   'XXX',
                'user_count' => 777,
                'fingerprint_count' => 123,
                'ip_address' => '0.0.0.5',
                'port' =>      4370,
                'status_at' => now(),
            ],
            [
                'biometric_device_status_id' => $biometric_statuses['active']->id,
                'area_id' => $areas['cas']->id,
                'name' =>    'CAS 1',
                'serial' =>  'XXXXX6',
                'model' =>   'XXX',
                'user_count' => 777,
                'fingerprint_count' => 123,
                'ip_address' => '0.0.0.6',
                'port' =>      4370,
                'status_at' => now(),
            ],
            [
                'biometric_device_status_id' => $biometric_statuses['active']->id,
                'area_id' => $areas['cas']->id,
                'name' =>    'CAS 2',
                'serial' =>  'XXXXX7',
                'model' =>   'XXX',
                'user_count' => 777,
                'fingerprint_count' => 123,
                'ip_address' => '0.0.0.7',
                'port' =>      4370,
                'status_at' => now(),
            ],
            [
                'biometric_device_status_id' => $biometric_statuses['active']->id,
                'area_id' => $areas['cas']->id,
                'name' =>    'CAS 3',
                'serial' =>  'XXXX8',
                'model' =>   'XXX',
                'user_count' => 777,
                'fingerprint_count' => 123,
                'ip_address' => '0.0.0.8',
                'port' =>      4370,
                'status_at' => now(),
            ],
            [
                'biometric_device_status_id' => $biometric_statuses['active']->id,
                'area_id' => $areas['cbm']->id,
                'name' =>    'CBM',
                'serial' =>  'XXXX9',
                'model' =>   'XXX',
                'user_count' => 777,
                'fingerprint_count' => 123,
                'ip_address' => '0.0.0.9',
                'port' =>      4370,
                'status_at' => now(),
            ],
            [
                'biometric_device_status_id' => $biometric_statuses['active']->id,
                'area_id' => $areas['cebrem']->id,
                'name' =>    'CEBREM',
                'serial' =>  'XXXX10',
                'model' =>   'XXX',
                'user_count' => 777,
                'fingerprint_count' => 123,
                'ip_address' => '0.0.0.10',
                'port' =>      4370,
                'status_at' => now(),
            ],
            [
                'biometric_device_status_id' => $biometric_statuses['active']->id,
                'area_id' => $areas['cfes']->id,
                'name' =>    'CFES',
                'serial' =>  'XXXX11',
                'model' =>   'XXX',
                'user_count' => 777,
                'fingerprint_count' => 123,
                'ip_address' => '0.0.0.11',
                'port' =>      4370,
                'status_at' => now(),
            ],
            [
                'biometric_device_status_id' => $biometric_statuses['active']->id,
                'area_id' => $areas['che']->id,
                'name' =>    'CHE',
                'serial' =>  'XXXX12',
                'model' =>   'XXX',
                'user_count' => 777,
                'fingerprint_count' => 123,
                'ip_address' => '0.0.0.12',
                'port' =>      4370,
                'status_at' => now(),
            ],
            [
                'biometric_device_status_id' => $biometric_statuses['active']->id,
                'area_id' => $areas['cisc']->id,
                'name' =>    'CISC',
                'serial' =>  'XXXX13',
                'model' =>   'XXX',
                'user_count' => 777,
                'fingerprint_count' => 123,
                'ip_address' => '0.0.0.13',
                'port' =>      4370,
                'status_at' => now(),
            ],
            [
                'biometric_device_status_id' => $biometric_statuses['active']->id,
                'area_id' => $areas['cmulhs']->id,
                'name' =>    'CMULHS',
                'serial' =>  'XXXX14',
                'model' =>   'XXX',
                'user_count' => 777,
                'fingerprint_count' => 123,
                'ip_address' => '0.0.0.14',
                'port' =>      4370,
                'status_at' => now(),
            ],
            [
                'biometric_device_status_id' => $biometric_statuses['active']->id,
                'area_id' => $areas['coe']->id,
                'name' =>    'COE',
                'serial' =>  'XXXX15',
                'model' =>   'XXX',
                'user_count' => 777,
                'fingerprint_count' => 123,
                'ip_address' => '0.0.0.15',
                'port' =>      4370,
                'status_at' => now(),
            ],
            [
                'biometric_device_status_id' => $biometric_statuses['active']->id,
                'area_id' => $areas['con']->id,
                'name' =>    'CON',
                'serial' =>  'XXXX16',
                'model' =>   'XXX',
                'user_count' => 777,
                'fingerprint_count' => 123,
                'ip_address' => '0.0.0.16',
                'port' =>      4370,
                'status_at' => now(),
            ],
            [
                'biometric_device_status_id' => $biometric_statuses['active']->id,
                'area_id' => $areas['cvm']->id,
                'name' =>    'CVM',
                'serial' =>  'XXXX17',
                'model' =>   'XXX',
                'user_count' => 777,
                'fingerprint_count' => 123,
                'ip_address' => '0.0.0.17',
                'port' =>      4370,
                'status_at' => now(),
            ],
            [
                'biometric_device_status_id' => $biometric_statuses['active']->id,
                'area_id' => $areas['odt']->id,
                'name' =>    'ODT',
                'serial' =>  'XXXX18',
                'model' =>   'XXX',
                'user_count' => 777,
                'fingerprint_count' => 123,
                'ip_address' => '0.0.0.18',
                'port' =>      4370,
                'status_at' => now(),
            ],
            [
                'biometric_device_status_id' => $biometric_statuses['active']->id,
                'area_id' => $areas['coed']->id,
                'name' =>    'CoEd 1',
                'serial' =>  'XXXX19',
                'model' =>   'XXX',
                'user_count' => 777,
                'fingerprint_count' => 123,
                'ip_address' => '0.0.0.19',
                'port' =>      4370,
                'status_at' => now(),
            ],
            [
                'biometric_device_status_id' => $biometric_statuses['active']->id,
                'area_id' => $areas['coed']->id,
                'name' =>    'CoEd 2',
                'serial' =>  'XXXX20',
                'model' =>   'XXX',
                'user_count' => 777,
                'fingerprint_count' => 123,
                'ip_address' => '0.0.0.20',
                'port' =>      4370,
                'status_at' => now(),
            ],
            [
                'biometric_device_status_id' => $biometric_statuses['active']->id,
                'area_id' => $areas['ogs']->id,
                'name' =>    'OGS',
                'serial' =>  'XXXX21',
                'model' =>   'XXX',
                'user_count' => 777,
                'fingerprint_count' => 123,
                'ip_address' => '0.0.0.21',
                'port' =>      4370,
                'status_at' => now(),
            ],
            [
                'biometric_device_status_id' => $biometric_statuses['active']->id,
                'area_id' => $areas['hospital']->id,
                'name' =>    'Hospital',
                'serial' =>  'XXXX22',
                'model' =>   'XXX',
                'user_count' => 777,
                'fingerprint_count' => 123,
                'ip_address' => '0.0.0.22',
                'port' =>      4370,
                'status_at' => now(),
            ],
            [
                'biometric_device_status_id' => $biometric_statuses['active']->id,
                'area_id' => $areas['library']->id,
                'name' =>    'Library',
                'serial' =>  'XXXX23',
                'model' =>   'XXX',
                'user_count' => 777,
                'fingerprint_count' => 123,
                'ip_address' => '0.0.0.23',
                'port' =>      4370,
                'status_at' => now(),
            ],
            [
                'biometric_device_status_id' => $biometric_statuses['active']->id,
                'area_id' => $areas['oasp']->id,
                'name' =>    'OASP',
                'serial' =>  'XXXX24',
                'model' =>   'XXX',
                'user_count' => 777,
                'fingerprint_count' => 123,
                'ip_address' => '0.0.0.24',
                'port' =>      4370,
                'status_at' => now(),
            ],
            [
                'biometric_device_status_id' => $biometric_statuses['active']->id,
                'area_id' => $areas['odt']->id,
                'name' =>    'ODT 2',
                'serial' =>  'XXXX25',
                'model' =>   'XXX',
                'user_count' => 777,
                'fingerprint_count' => 123,
                'ip_address' => '0.0.0.25',
                'port' =>      4370,
                'status_at' => now(),
            ],
            [
                'biometric_device_status_id' => $biometric_statuses['active']->id,
                'area_id' => $areas['osa']->id,
                'name' =>    'OSA',
                'serial' =>  'XXXX26',
                'model' =>   'XXX',
                'user_count' => 777,
                'fingerprint_count' => 123,
                'ip_address' => '0.0.0.26',
                'port' =>      4370,
                'status_at' => now(),
            ],
            [
                'biometric_device_status_id' => $biometric_statuses['active']->id,
                'area_id' => $areas['prio']->id,
                'name' =>    'PRIO',
                'serial' =>  'XXXX27',
                'model' =>   'XXX',
                'user_count' => 777,
                'fingerprint_count' => 123,
                'ip_address' => '0.0.0.27',
                'port' =>      4370,
                'status_at' => now(),
            ],
            [
                'biometric_device_status_id' => $biometric_statuses['active']->id,
                'area_id' => $areas['extension']->id,
                'name' =>    'RDE',
                'serial' =>  'XXXX28',
                'model' =>   'XXX',
                'user_count' => 777,
                'fingerprint_count' => 123,
                'ip_address' => '0.0.0.28',
                'port' =>      4370,
                'status_at' => now(),
            ],
            [
                'biometric_device_status_id' => $biometric_statuses['active']->id,
                'area_id' => $areas['orgm']->id,
                'name' =>    'ORGM',
                'serial' =>  'XXXX29',
                'model' =>   'XXX',
                'user_count' => 777,
                'fingerprint_count' => 123,
                'ip_address' => '0.0.0.29',
                'port' =>      4370,
                'status_at' => now(),
            ],
            [
                'biometric_device_status_id' => $biometric_statuses['active']->id,
                'area_id' => $areas['oss']->id,
                'name' =>    'OSS',
                'serial' =>  'XXXX30',
                'model' =>   'XXX',
                'user_count' => 777,
                'fingerprint_count' => 123,
                'ip_address' => '0.0.0.30',
                'port' =>      4370,
                'status_at' => now(),
            ],
            [
                'biometric_device_status_id' => $biometric_statuses['active']->id,
                'area_id' => $areas['ucc']->id,
                'name' =>    'UCC',
                'serial' =>  'XXXX31',
                'model' =>   'XXX',
                'user_count' => 777,
                'fingerprint_count' => 123,
                'ip_address' => '0.0.0.31',
                'port' =>      4370,
                'status_at' => now(),
            ],
            [
                'biometric_device_status_id' => $biometric_statuses['active']->id,
                'area_id' => $areas['ucc']->id,
                'name' =>    'UCC 2',
                'serial' =>  'XXXX32',
                'model' =>   'XXX',
                'user_count' => 777,
                'fingerprint_count' => 123,
                'ip_address' => '0.0.0.32',
                'port' =>      4370,
                'status_at' => now(),
            ],
            [
                'biometric_device_status_id' => $biometric_statuses['active']->id,
                'area_id' => $areas['uh']->id,
                'name' =>    'UH',
                'serial' =>  'XXXX33',
                'model' =>   'XXX',
                'user_count' => 777,
                'fingerprint_count' => 123,
                'ip_address' => '0.0.0.33',
                'port' =>      4370,
                'status_at' => now(),
            ],


        ];

        foreach ($data as $item) {
            BiometricDevice::create($item);
        }
    }
}
