/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "index": [],
    "store": [],
    "attachments.destroy": [
        {
            "name": "attachment",
            "required": true
        }
    ],
    "checks.destroy": [
        {
            "name": "check",
            "required": true
        }
    ],
    "login.index": [],
    "login.store": [],
    "login.logout": [],
    "dashboard.index": [],
    "dashboard.checks.index": [],
    "dashboard.employees.index": [],
    "dashboard.departments.index": [],
    "dashboard.colleges.index": [],
    "dashboard.users.index": [],
    "dashboard.profile.index": [],
    "dashboard.profile.store": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
