/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "index": [],
    "store": [],
    "attachments.destroy": [
        {
            "name": "attachment",
            "required": true
        }
    ],
    "checks.destroy": [
        {
            "name": "check",
            "required": true
        }
    ],
    "login.index": [],
    "login.store": [],
    "forgot.index": [],
    "forgot.store": [],
    "forgot.show": [
        {
            "name": "forgot",
            "required": true
        }
    ],
    "forgot.edit": [
        {
            "name": "forgot",
            "required": true
        }
    ],
    "forgot.update": [
        {
            "name": "forgot",
            "required": true
        }
    ],
    "login.logout": [],
    "dashboard.index": [],
    "dashboard.checks.index": [],
    "dashboard.employees.index": [],
    "dashboard.offices.index": [],
    "dashboard.colleges.index": [],
    "dashboard.users.index": [],
    "dashboard.users.create": [],
    "dashboard.users.store": [],
    "dashboard.users.edit": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "dashboard.users.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "dashboard.users.destroy": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "dashboard.profile.index": [],
    "dashboard.profile.store": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
