/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "boost.browser-logs": [],
    "sanctum.csrf-cookie": [],
    "index": [],
    "store": [],
    "camera.index": [],
    "records.index": [],
    "records.update": [
        {
            "name": "record",
            "required": true
        }
    ],
    "records.destroy": [
        {
            "name": "record",
            "required": true
        }
    ],
    "attachments.destroy": [
        {
            "name": "attachment",
            "required": true
        }
    ],
    "checks.destroy": [
        {
            "name": "check",
            "required": true
        }
    ],
    "login.index": [],
    "login.store": [],
    "forgot.index": [],
    "forgot.store": [],
    "forgot.show": [
        {
            "name": "forgot",
            "required": true
        }
    ],
    "forgot.edit": [
        {
            "name": "forgot",
            "required": true
        }
    ],
    "forgot.update": [
        {
            "name": "forgot",
            "required": true
        }
    ],
    "login.logout": [],
    "dashboard.index": [],
    "dashboard.check-status.index": [],
    "dashboard.check-status.update": [
        {
            "name": "check_status",
            "required": true
        }
    ],
    "dashboard.checks.index": [],
    "dashboard.checks.show": [
        {
            "name": "check",
            "required": true
        }
    ],
    "dashboard.checks.update": [
        {
            "name": "check",
            "required": true
        }
    ],
    "dashboard.checks.destroy": [
        {
            "name": "check",
            "required": true
        }
    ],
    "dashboard.employees.index": [],
    "dashboard.employees.create": [],
    "dashboard.employees.store": [],
    "dashboard.employees.show": [
        {
            "name": "employee",
            "required": true,
            "binding": "id"
        }
    ],
    "dashboard.employees.edit": [
        {
            "name": "employee",
            "required": true,
            "binding": "id"
        }
    ],
    "dashboard.employees.update": [
        {
            "name": "employee",
            "required": true,
            "binding": "id"
        }
    ],
    "dashboard.employees.destroy": [
        {
            "name": "employee",
            "required": true,
            "binding": "id"
        }
    ],
    "dashboard.offices.index": [],
    "dashboard.offices.create": [],
    "dashboard.offices.store": [],
    "dashboard.offices.show": [
        {
            "name": "office",
            "required": true
        }
    ],
    "dashboard.offices.edit": [
        {
            "name": "office",
            "required": true,
            "binding": "id"
        }
    ],
    "dashboard.offices.update": [
        {
            "name": "office",
            "required": true,
            "binding": "id"
        }
    ],
    "dashboard.offices.destroy": [
        {
            "name": "office",
            "required": true,
            "binding": "id"
        }
    ],
    "dashboard.colleges.index": [],
    "dashboard.colleges.create": [],
    "dashboard.colleges.store": [],
    "dashboard.colleges.show": [
        {
            "name": "college",
            "required": true
        }
    ],
    "dashboard.colleges.edit": [
        {
            "name": "college",
            "required": true,
            "binding": "id"
        }
    ],
    "dashboard.colleges.update": [
        {
            "name": "college",
            "required": true,
            "binding": "id"
        }
    ],
    "dashboard.colleges.destroy": [
        {
            "name": "college",
            "required": true,
            "binding": "id"
        }
    ],
    "dashboard.users.index": [],
    "dashboard.users.create": [],
    "dashboard.users.store": [],
    "dashboard.users.show": [
        {
            "name": "user",
            "required": true
        }
    ],
    "dashboard.users.edit": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "dashboard.users.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "dashboard.users.destroy": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "dashboard.profile.index": [],
    "dashboard.profile.store": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
